name: education_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.7.0
  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^5.5.0
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  image_picker: ^1.0.4
  intl: ^0.18.0
  lottie: ^2.6.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.14
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  firebase_ui_auth: ^1.7.0
  firebase_auth: ^4.10.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/vectors/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonic/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonic/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonic/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets\fonts\aeonic\AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets\fonts\aeonic\AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets\fonts\aeonic\AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins\Poppins-Thin.ttf
          weight: 100
        - asset: assets\fonts\Poppins\Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Poppins\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins\Poppins-Bold.ttf
          weight: 700
        - asset: assets\fonts\Poppins\Poppins-ExtraBold.ttf
          weight: 800